################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

- sections:
  - title: Getting Started
    link: docs/getting-started.md
- sections:   
  - title: Consumer Management
    link: docs/Consumer/api-integration-homePage.md
    sections:
    - title: create a Consumer
      link: docs/Consumer/CreateConsumer.md
    - title: list of consumer
      link: docs/Consumer/ListConsumer.md
    - title: Get consumer
      link: docs/Consumer/GetConsumer.md
    - title: Update consumer
      link: docs/Consumer/UpdateConsumer.md
    - title: set consumer status
      link: docs/Consumer/SetConsumerStatus.md
    - title: Lists all apps
      link: docs/Consumer/LisTApps.md
    - title: Creates an app
      link: docs/Consumer/CreateApp.md
    - title: Update app
      link: docs/Consumer/UpdateApp.md
    - title: Get Consumer app
      link: docs/Consumer/GetApp.md
    - title: Approve, revoke, or generate API key for consumer app
      link: docs/Consumer/ApproveRevokeApp.md
  - title: Product Management
    link: docs/Consumer/api-integration-homePage.md
    sections:
    - title: create a Product
      link: docs/Consumer/CreateProduct.md
    - title: list of Products
      link: docs/Consumer/ListProduct.md
    - title: Get Product
      link: docs/Consumer/GetProduct.md
    - title: Update Product
      link: docs/Consumer/UpdateProduct.md
  - title: Rateplan Management
    link: docs/Consumer/api-integration-homePage.md
    sections:
    - title: create a Rateplan 
      link: docs/Consumer/CreateRateplan.md
    - title: list of Rateplan
      link: docs/Consumer/ListRateplan.md
    - title: Get Rateplan
      link: docs/Consumer/GetRateplan.md
    - title: Update Rateplan
      link: docs/Consumer/UpdateRateplan.md   
  - title: Subscription Management
    link: docs/Consumer/api-integration-homePage.md
    sections:
    - title: create a Subscription 
      link: docs/Consumer/CreateSubscription.md
    - title: list of Subscription
      link: docs/Consumer/ListSubscription.md
    - title: Get Subscription
      link: docs/Consumer/GetSubscription.md
    - title: Expire Subscription
      link: docs/Consumer/ExpireSubscription.md 
  - title: Reports Management
    link: docs/Consumer/api-integration-homePage.md
    sections:
    - title: create a Queries
      link: docs/Consumer/CreateQueries.md
    - title: list of Queries
      link: docs/Consumer/ListQueries.md
    - title: Get Queries
      link: docs/Consumer/GetQueries.md
    - title: Get a Query Result
      link: docs/Consumer/GetQueryResult.md
    - title: Get a Query Result URL
      link: docs/Consumer/GetQueryResultURL.md
    - title: Lists Custom Report
      link: docs/Consumer/ListReport.md
    - title: Creates Custom Report
      link: docs/Consumer/CreateReport.md
    - title: Update Custom Report
      link: docs/Consumer/UpdateReport.md
    - title: Get Custom Report
      link: docs/Consumer/GetReport.md
   
     
      
